# General
book_font: "Gotham"
book_color: "0E4C85"

# Cover
cover_title_y: 8.16
cover_text_padding_right: 0
cover_title_font_size: 20
cover_title_font_style: ""
cover_color:

has_image: 1
cover_user_image_y: 5.0333
cover_user_image_max_height: 3.3635
cover_user_image_max_width: 5

tag_lines: 1
max_tag_line_1_length: 32
max_tag_line_2_length:
max_tag_line_3_length:
max_tag_line_4_length:

# Inner cover
show_book_title_on_inner_cover: 1
inner_cover_title_y: 7.994
inner_cover_font_size: 20

# Sections
header_color:
section_header_y: 6.875
headers_font_size: 26
headers_font_style: "B"
header_color: "FFFFFF"
section_user_image_max_height: 3.3333
section_user_image_max_width: 5
section_user_image_y: 6.2417

# Table of content
toc_header_y: 7.750