# General
book_font: "Times"
book_color: "983918"

# Cover
cover_title_y: 2
cover_text_padding_right: 0
cover_title_font_size: 12
cover_title_font_style: "I"
cover_color:

has_image: 1
cover_user_image_y: 5.260
cover_user_image_max_height: 2.3622
cover_user_image_max_width: 2.87402

tag_lines: 2
max_tag_line_1_length: 26
max_tag_line_2_length: 26
max_tag_line_3_length: 50
max_tag_line_4_length: 50

# Inner cover
inner_cover_title_y: 2
inner_cover_font_size: 12
show_book_title_on_inner_cover: 1

# Sections
header_color:
section_header_y: 6
headers_font_size: 20
headers_font_style: "I"
section_user_image_y: 5.4
section_user_image_max_height: 3.74016
section_user_image_max_width: 3.14961

# Table of content
toc_header_y: 7.2