# General
book_font: "Times"
book_color: "224D70"

# Cover
cover_title_y: 2.69
cover_text_padding_right: 0
cover_title_font_size: 12
cover_title_font_style: "I"

has_image: 0
cover_user_image_y:
cover_user_image_max_height:
cover_user_image_max_width:
cover_color:

tag_lines: 2
max_tag_line_1_length: 40
max_tag_line_2_length: 40
max_tag_line_3_length:
max_tag_line_4_length:

# Inner cover
inner_cover_title_y:
inner_cover_font_size:
show_book_title_on_inner_cover:

# Sections
header_color:
section_header_y: 6
headers_font_size: 20
headers_font_style: ""
section_user_image_y: 4.80
section_user_image_max_height: 3.93701
section_user_image_max_width: 3.93701

# Table of content
toc_header_y: 6.8